# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOTLTE_EUR_OPEN) := \
	exynos7885-jackpotlte_eur_open_03.dtb \
	exynos7885-jackpotlte_eur_open_04.dtb \
	exynos7885-jackpotlte_eur_open_05.dtb \
	exynos7885-jackpotlte_eur_open_06.dtb \
	exynos7885-jackpotlte_eur_open_07.dtb 

dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOT2LTE_EUR_OPEN) := \
	exynos7885-jackpot2lte_eur_open_03.dtb \
	exynos7885-jackpot2lte_eur_open_04.dtb \
	exynos7885-jackpot2lte_eur_open_05.dtb \
	exynos7885-jackpot2lte_eur_open_06.dtb \
	exynos7885-jackpot2lte_eur_open_07.dtb 

dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOTLTE_CAN_OPEN) := \
	exynos7885-jackpotlte_can_open_03.dtb \
	exynos7885-jackpotlte_can_open_04.dtb \
	exynos7885-jackpotlte_can_open_05.dtb \
	exynos7885-jackpotlte_can_open_06.dtb \
	exynos7885-jackpotlte_can_open_07.dtb 
	
dtb-$(CONFIG_MACH_EXYNOS7885_A7Y18_OPEN) := \
	exynos7885-a7y18lte_eur_open_00.dtb \
	exynos7885-a7y18lte_eur_open_01.dtb \
	exynos7885-a7y18lte_eur_open_03.dtb 

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
